config/routes.rb
Rails.application.routes.draw do

  post '/api/1/q/token' => 'q#token'
  post '/api/1/q/register' => 'q#register'
  post '/api/1/q/deregister' => 'q#deregister'
  post '/api/1/q/subscribe' => 'q#subscribe'
  post '/api/1/q/unsubscribe' => 'q#unsubscribe'
  post '/api/1/q/event' => 'q#event'

  put '/admin/q/:id' => 'admin/q#update'
  delete '/admin/q/:id' => 'admin/q#destroy'
  post '/admin/q' => 'admin/q#create'
  get '/admin/q/:id/users' => 'admin/q#users'
  get '/admin/q/:id/events' => 'admin/q#events'
  get '/admin/q/:id/sent' => 'admin/q#sent'
  match '/admin/q/:id/klasses/:klass_id' => 'admin/q#klasses'
  match '/admin/q/:id/klasses' => 'admin/q#klasses'
  get '/admin/q/:id/subscriptions' => 'admin/q#subscriptions'
  match '/admin/q/:id' => 'admin/q#show'
  get '/admin/q' => 'admin/q#index'

  match '/admin/dj' => 'admin/dj#index'

  match '/users/sign_in' => 'account#sign_in'
  match '/users/sign_out' => 'account#sign_out'
  match '/users/sign_up' => 'account#sign_up'
  match '/users/edit' => 'account#edit'
  match '/users/forgotten' => 'account#forgotten'
  get   '/users/reset/:code' => 'account#reset'

  namespace "admin" do
    resources :snippet
    resources :mapping
    resources :layouts
    resources :page_templates
    resources :blocks
    resources :calendars
    resources :calendar_entries
    resources :views
    resources :page_template_terms
    resources :form_field_types 
    resources :form_field_groups 
    resources :form
    resources :ad_units
    resources :ad_zones
    resources :ads
    resources :notices
    resources :goals
    resources :experiments
  end

  get '/repo' => 'repo#index'

  get '/plumb' => 'admin/dashboard#plumb'
  get '/admin/salesforce' => 'admin/dashboard#salesforce'
  get '/admin/goals/:id/scores' => 'admin/goals#scores'
  get '/admin/engagements' => 'admin/kit_engagement#index'
  post '/admin/ad/:id/activate/:mode' => 'admin/ads#activate'
  post '/admin/ad_unit/:id/create_block' => 'admin/ad_units#create_block'
  post '/admin/ad_zone/:id/create_block' => 'admin/ad_zone#create_block'
  get '/admin/advertisments' => 'admin/advertisments#index'
  get '/admin/orders' => 'admin/order#index'
  get '/admin/order/:id' => 'admin/order#show'
  get '/admin/order/payment/:id' => 'admin/order#payment'

  post '/ad/buy' => 'ad#buy'
  get '/ad/clicked/:id' => 'ad#clicked'
  post "/order/pay_for_tickets" => 'order#pay_for_tickets'
  post "/order/pay_for_ads" => 'order#pay_for_ads'
  get '/order/sp/success' => 'order#sage_pay_success'
  get '/order/sp/failure' => 'order#sage_pay_failure'

  match "/admin/form_field_types/:id/editoptions" => "admin/form_field_types#editoptions", :only=>[:get, :put]
  match "/calendar/entry" => "calendar#update_entry", :only=>[:put, :post]
  post "/calendar/sell_tickets_setup" => "calendar#sell_tickets_setup"
  get "/admin/calendar_entries/:id/sold" => "admin/calendar_entries#sold" 
  post "/admin/calendar_entries/:id" => "admin/calendar_entries#show" 
  get "/admin/calendars/:calendar_id/:start_date/:id" => "admin/calendar_entries#show"
  get "/admin/page_templates/:id/pages" => "admin/page_templates#pages"
  get "/admin/page_templates/:id/mapping" => "admin/page_templates#mapping"
  match "/tickets/:item_model/:item_id" => "calendar#buy_tickets"
  get "/tickets/sold_as_csv/:item_model/:item_id" => "calendar#sold_as_csv"

  get "/form/:id"  => "form#show"
  post "/form/:id" => "form#save"
  match "/form/search/:form_id" => "form#search"
  get "/admin/forms" => "admin/form#index"
  get "/admin/form/:id/generate_html" => "admin/form#generate_html"
  get "/admin/form/submission/:id" => "admin/form#show_submission"
  delete "/admin/form/submission/:id" => "admin/form#delete_submission"
  post "/admin/form/submission/:id/destroy" => "admin/form#destroy_submission"
  post "/admin/form/submission/:id/showhide/:mode" => "admin/form#show_hide_submission"
  post "/admin/form/submission/:id" => "admin/form#update_submission"
  match "/admin/form/:id/field/:field_id" => "admin/form#field", :only=>[:get, :post]
  get "/admin/form/:id/fields" => "admin/form#fields"
  post "/admin/form/:id/fields" => "admin/form#update_fields"
  get "/admin/forms/:id/list" => "admin/form#list"
  get "/admin/forms/:id/browse" => "admin/form#browse"
  get "/admin/forms/:id/export" => "admin/form#export"

#  get "/kit/css/*path" => "admin/html_asset#serve"
#  get "/kit/js/*path" => "admin/html_asset#serve"
  get "admin/html_assets" => "admin/html_asset#index"
  get "admin/html_asset/:id" => "admin/html_asset#show"
  post "admin/html_asset/:id" => "admin/html_asset#update"
  put "admin/html_asset" => "admin/html_asset#create"
  delete "admin/html_asset/:id" => "admin/html_asset#destroy"

  put 'admin/gallery/image/:id/update' => 'admin/gallery#update_image'
  get "admin/gallery/:id/edit" => "admin/gallery#edit"
  get "admin/gallery/:id/preview" => "admin/gallery#view"
  get "admin/gallery/:id" => "admin/gallery#show"
  get "admin/galleries" => "admin/gallery#index"
  delete "admin/gallery/:id" => "admin/gallery#delete"
  post "admin/galleries" => "admin/gallery#create"
  put "admin/gallery/:id" => "admin/gallery#update"

  post "admin/gallery/:id/images/sort" => "admin/gallery#sort_images"
  post "admin/gallery/:id/image/:image_id" => "admin/gallery#add_image"
  delete "admin/gallery/:id/image/:image_id" => "admin/gallery#delete_image"
  
  match 'db/analytics/setup' => 'admin/analytics#setup', :only=>[:get, :post]
  get 'db/analytics' => 'admin/analytics#index'

  get 'admin/dashboard/logfile' => 'admin/dashboard#logfile' 
  post 'admin/dashboard/user_comment/:id' => 'admin/dashboard#user_comment'
  get 'admin/dashboard/user_comments' => 'admin/dashboard#user_comments'
  match 'admin/dashboard/errors' => 'admin/dashboard#events', :only=>[:get, :delete]
  get 'admin/dashboard/error/:id' => 'admin/dashboard#event' 
  post 'admin/dashboard/maintenance' => 'admin/dashboard#maintenance'
  put 'admin/system/:attr' => 'admin/dashboard#update_preference'
  post 'admin/system/:attr/:value' => 'admin/dashboard#system_settings'
  match 'admin/system' => 'admin/dashboard#system'
  get 'admin/sysadmin' => 'admin/dashboard#sysadmin'
  get 'admin/integrity' => 'admin/dashboard#integrity'

  get 'db/error' => 'admin/dashboard#error'
  get 'db/help(/:url)' => 'admin/dashboard#help'
  get 'db' => 'admin/dashboard#index'

  get 'admin/help/images' => 'admin/help#images'
  delete 'admin/help/image/:id' => 'admin/help#delete_image'
  post 'admin/help/upload' => 'admin/help#upload'
  get 'admin/helps' => 'admin/help#index'
  get 'admin/help/:id/edit' => 'admin/help#edit'
  delete "admin/help/:id" => 'admin/help#destroy'
  post 'admin/helps' => 'admin/help#create'
  post 'admin/help/:id' => 'admin/help#update'

  post 'convo/suggest_game' => 'messaging#suggest_game'
  post 'convo/game/:game_id/start/:opponent_id' => 'messaging#game_start'
  post 'convo/game/:id/:available' => 'messaging#game_availability'
  put 'convo/:id' => 'messaging#message'
  post 'convo' => 'messaging#poll'
  get 'convo/:id' => 'messaging#show_conversation'
  get 'convo' => 'messaging#index'

  get 'mercury/modals/media' => 'images#media_modal'
  get 'mercury/modals/htmleditor.html' => 'utility#mercury_html'
  get 'mercury/images' => 'images#index'
  match 'mercury/images/browse' => 'images#index'
  put 'mercury/images/:id' => 'images#update'
  post 'mercury/images' => 'images#create'
  match 'mercury/links' => 'links#index'
  scope '/mercury' do
          match ':type/:resource' => "mercury#resource"
          match 'snippets/:name/options' => "mercury#snippet_options"
          match 'snippets/:name/preview' => "mercury#snippet_preview"
  end
 
  get "menus/new/:mode" => 'menu#new' 
  get "menus" => 'menu#index'
  put "menu" => 'menu#create'
  get "menu/:id" => "menu#show"
  match "menu/:id/add" => "menu#add", :only=>[:put, :post]
  post "menu/:id/move" => "menu#move"
  get "menu/:id/promote/:item_id/:parent_id" => "menu#promote"
  delete "menu/item/:id" => "menu#delete_item"
  delete "menu/:id" => "menu#delete"
  get "menu/:id/edit/:item_id" => "menu#edit"
  
  put "asset/:id/tags" => 'asset#tags'
  put "asset/:id" => 'asset#update'
  delete "asset/:id" => "asset#delete"
#  get "admin/asset/:id" => "asset#show" ???? not sure we need this???
  get "asset/:id" => "asset#show"
  post "assets" => "asset#create"
  match "assets" => "asset#index"
  get "file/:id/:code/:name" => "asset#get"

  get "/db/content/analyse/:id" => "admin/content#analyse"
  get "/db/content/match/:id" => "admin/content#match"
  get "category/browse" => 'category#browse'
  post "category/move" => 'category#move'
  post "category/delete/:id" => 'category#delete'  
  post "category/rename/:id" => 'category#rename'  
  post "category/new/:parent_id" => 'category#new'
  post "category/:id/public/:public" => 'category#permission_public'
  post "category/:id/permissions/subs" => 'category#permission_sub'
  post "category/:id/permission/:group_id/:mode/:granted" => 'category#permission'
  get "category/:id/permissions" => 'category#permissions'

  # this is only needed to give friendly URL's - we don't actually respond to the requests using this route
  resources :asset # DO WE NEED THIS???

  match 'blocks/:id/options' => "blocks#options"
  get 'blocks/:id/preview' => "blocks#preview"
  get 'blocks/:id/render' => "blocks#preview"
  get 'blocks/:name/instance' => 'blocks#preview_by_name'
  post 'blocks/:id/preview/:page_id' => "blocks#store"
  get 'blocks/:page_id/:mercury_id' => 'blocks#show'
  get 'blocks/:page_id' => 'blocks#index'

  get 'admin/formats' => 'utility#snippet_list'
  get 'admin/format/:id' => 'admin/snippet#fetch'

  get 'admin/block_instance/new/:id' => 'admin/block_instance#create'
  get 'admin/block_instances' => 'admin/block_instance#index'
  get 'admin/block_instance/:id/edit' => 'admin/block_instance#edit'
  get 'admin/block_instance/:id' => 'admin/block_instance#show'

app/models/form_field_group.rb
class FormFieldGroup < ActiveRecord::Base
  belongs_to :form
  has_many :form_fields, :order=>:display_order
end

app/controllers/admin/form_field_groups_controller.rb
class Admin::FormFieldGroupsController < AdminController

  def index
    @form = Form.sys(_sid).where(:id=>params[:form_id]).first
    redirect_to "/admin/forms", :notice=>"Can't find that field group" and return unless @form
    @form_field_groups = @form.form_field_groups
  end

  def show
    @form_field_group = FormFieldGroup.find_sys_id(_sid, params[:id])
    @form = @form_field_group.form
  end

  def new
    @form = Form.sys(_sid).where(:id=>params[:form_id]).first
    @form_field_group = FormFieldGroup.new
    @form_field_group.form = @form
    @form_field_group.order_by = @form.form_field_groups.last.order_by + 100 rescue 100
  end

  def create
    @form_field_group = FormFieldGroup.new(params[:form_field_group])
    @form_field_group.system_id = _sid
    if @form_field_group.save
      redirect_to [:admin, @form_field_group], :notice => "Successfully created field group"
    else
      render :action => 'new'
    end
  end

  def edit
    @form_field_group = FormFieldGroup.find_sys_id(_sid, params[:id])
    @form = @form_field_group.form
  end

  def update
    @form_field_group = FormFieldGroup.find_sys_id(_sid, params[:id])
    if @form_field_group.update_attributes(params[:form_field_group])
      redirect_to [:admin, @form_field_group], :notice  => "Successfully updated field group"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @form_field_group = FormFieldGroup.find_sys_id(_sid, params[:id])
    form_id = @form_field_group.form_id
    @form_field_group.destroy
    redirect_to "/admin/form_field_groups?form_id=#{form_id}", :notice => "Successfully delete field group"
  end
end

app/helpers/admin/form_field_groups_helper.rb
module Admin::FormFieldGroupsHelper
end

app/views/admin/form_field_groups/_form.html.haml
.cms_form.validated
  = form_for [:admin, @form_field_group] do |f|
    = f.error_messages
    = f.hidden_field :form_id

    %p
      = f.label :name
      = f.text_field :name, :class=>"required"

    %p
      = f.label "Top of group Text"
      = f.text_area :intro
      .field_help
        This text appears at the top of the group, above any fields it contains

    %p
      = f.label "Bottom of group Text"
      = f.text_area :outro
      .field_help
        This text appears at the bottom of the group, below any fields it contains

    %p
      = f.label "Class"
      = f.text_field :klass
      .field_help
        CSS class name(s) to attach to the fieldset used to render this group

    %p
      = f.label "Display Order"
      = f.text_field :order_by, :class=>"number"
      .field_help
        A numeric value indicating the relative position of this group - lower numbered groups are shown first, higher numbered groups last

    %p
      = kit_submit "Save"

app/views/admin/form_field_groups/edit.html.haml
- content_for :main do
  
  %h1.forms_icon Field Group for Form '#{@form.title}'

  = render 'form'

  %p
    = icon_to "Field Groups", "/admin/form_field_groups?form_id=#{@form.id}"
    = icon_to 'Form', admin_form_path(@form)

app/views/admin/form_field_groups/index.html.haml
- content_for :main do
  
  %h1.forms_icon Field Groups for Form '#{@form.title}'

  %table
    %tr
      %th Name
      %th Display Order
      %th Last Updated
      %th &nbsp;

    - for form_field_group in @form_field_groups
      %tr
        %td= form_field_group.name
        %td= form_field_group.order_by
        %td= form_field_group.updated_at.to_s(:short)
        %td= icon_to "Show", "/admin/form_field_groups/#{form_field_group.id}"


  .top_space
    = icon_to "New Field Group", "/admin/form_field_groups/new?form_id=#{@form.id}"

app/views/admin/form_field_groups/new.html.haml
- content_for :main do
  
  %h1.forms_icon Field Group for Form '#{@form.title}'

  = render 'form'

  %p
    = icon_to "Field Groups", "/admin/form_field_groups?form_id=#{@form.id}"
    = icon_to 'Form', admin_form_path(@form)

app/views/admin/form_field_groups/show.html.haml
- content_for :main do
  
  %h1.forms_icon Field Group '#{@form_field_group.name}' for Form '#{@form_field_group.form.title}'

  .cms_form
    %p
      %label Name
      = @form_field_group.name

    %p
      %label Top of group Text
      = @form_field_group.intro

    %p
      %label Bottom of group Text
      = @form_field_group.outro

    %p
      %label Class
      = @form_field_group.klass

    %p
      %label Display Order
      = @form_field_group.order_by

    %p
      %label Last Updated
      = time_ago_in_words(@form_field_group.updated_at)

  
  %p
    = icon_to "Edit", edit_admin_form_field_group_path(@form_field_group)
    = link_to "Delete", [:admin, @form_field_group], :confirm => 'Are you sure?', :method => :delete, :class=>"action"
    = icon_to "Form Groups", admin_form_field_groups_path + "?form_id=#{@form.id}"
    = icon_to "Form", "/admin/form/#{@form.id}"
    = icon_to "Form Fields", "/admin/form/#{@form.id}/fields"